#!/bin/sh

COMMIT_MSG_FILE=$1

MESSAGE=$(cat $COMMIT_MSG_FILE)

if cog verify "$MESSAGE"; then
    echo "Commit parse succeeded"
elif [[ "$MESSAGE" = "Release"* ]]; then
    echo "Commit parse succeeded"
    echo "chore: 🏷️ $MESSAGE" >$COMMIT_MSG_FILE
else
    echo "See https://www.conventionalcommits.org/en/v1.0.0"
    exit 1
fi
